@startuml componentDiagram

skinparam linetype ortho
title "Pantry Hero Component Diagram"

component "Presentation Layer" {
    [User Interface]
    [Next.js\nComponents]
}

component "Business Layer" {
    [Auth Session\nProvider] -[hidden]> [Requests Lib]
    [Requests Lib] -[hidden]> [Next.js Server]
    [Next.js Server] -[hidden]> [Barcode Scan Lib]
    
}

component "Data Layer" {
    [Prisma ORM/GET + POST]
}

component "External Systems" {
    [Recipes API]
    [Barcode API]
} 

component "Service Layer" {
    [Service Interface]
    [Message Types]
}


[User] -d-> [Presentation Layer]
[Presentation Layer] -d-> [Business Layer]
[Business Layer] -d-> [Data Layer]
[Data Layer] -r-> [Supabase DB]
[External Systems] -d-> [Service Layer]
[Service Layer] -d-> [Next.js Server]

@endum