import './globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/navbar';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return(
    <html lang="en">
      <body className="flex flex-col min-h-screen">
      <div className="fixed z-50 w-full h-16 max-w-lg -translate-x-1/2 bg-red-100 border border-gray-200 rounded-full bottom-4 left-1/2 dark:bg-gray-700 dark:border-gray-600">

          {children}
          <footer>
          <Navbar/>
          </footer>
        </div>
      </body>
    </html>
  );
}
